# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_URL',
            field=models.CharField(max_length=2500),
        ),
    ]
